/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vertx.grpc

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertNotNull(App(), "app should have a greeting")
    }
}
